script:
  - mkdir context
  - cd context
  - wget http://minimals.contextgarden.net/setup/first-setup.sh
  - sh first-setup.sh --modules=all > /dev/null
  - source tex/setuptex
  - context ../Hello-world.tex

addons:
  artifacts:
    paths:
      - $(ls $HOME/*.pdf)
  s3_region: "eu-west-1"
