script:
  - mkdir context
  - cd context
  - wget http://minimals.contextgarden.net/setup/first-setup.sh
  - sh first-setup.sh --modules=all > /dev/null
  - source tex/setuptex
  - cd ..
  - context Hello-world.tex

addons:
  artifacts:
    debug: true
    paths:
      - $(ls $HOME/ofosos/fhb-recipes/*.pdf)
  s3_region: "eu-west-1"
